const QUERY_KEY = {
  AUTH: 'auth',
  PROFILE: 'profile',
  CHANGE_PASSWORD: 'change-password',
  ORDER: 'order',
  COURSES_DISCOUNTED: 'discounted-courses',
  COURSES_FREE: 'free-courses',
  INSTRUCTOR_COURSE: 'instructor-course',
  INSTRUCTOR_CHAPTER: 'instructor-chapter',
  INSTRUCTOR_LESSON: 'instructor-lesson',
  INSTRUCTOR_COURSE_VALIDATE: 'instructor-course-validate',
  INSTRUCTOR_CHECK_COURSE_COMPLETED: 'instructor-check-course-completed',
  INSTRUCTOR_CHAPTER_DETAIL: 'instructor-chapter-detail',
  INSTRUCTOR_LESSON_CODING: 'instructor-lesson-coding',
  INSTRUCTOR_GET_PARTICIPATED_COURSE: 'instructor-get-participated-courses',
  INSTRUCTOR_LIVE_SESSIONS: 'instructor-live-sessions',
  INSTRUCTOR_WALLET: 'instructor-wallet',
  INSTRUCTOR_LEARNER: 'instructor-learner',
  INSTRUCTOR_WITH_DRAW_REQUEST: 'instructor-with-draw-request',
  INSTRUCTOR_COUPON: 'instructor-coupon',
  CATEGORY: 'categories',
  COURSE: 'course',
  QA_SYSTEM: 'qa-systems',
  POSTS: 'posts',
  BLOGS: 'blogs',
  BLOG_DETAILS: 'blog-details',
  WISH_LIST: 'wish-list',
  SEARCH: 'search',
  VALIDATE_COURSE: 'validate-course',
  INSTRUCTOR_QUIZ: 'instructor-quiz',
  INSTRUCTOR_QUESTION: 'instructor-question',
  INSTRUCTOR_LESSON_VIDEO: 'instructor-lesson-video',
  INSTRUCTOR_LESSON_DOCUMENT: 'instructor-lesson-document',
  USER_NOTIFICATION: 'user-notification',
  USER_GET_MY_COURSES: 'user-get-my-courses',
  USER_GET_MY_COUPONS: 'user-get-my-coupons',
  LEARNING_PATH_LESSON: 'learning-path-lesson',
  LIVE_SESSION_CLIENT: 'live-session-client',
  LEARNING_PATH_PROGRESS: 'learning-path-progress',
  SUPPORT_BANKS: 'support-banks',
  COURSE_PROGRESS: 'course-progress',
  LESSON_COMMENT: 'lesson-comment',
  CERTIFICATE: 'certificate',
  NOTE_LESSON: 'note-lesson',
  INSTRUCTOR_REVENUE: 'instructor-revenue',
}

export default QUERY_KEY
